### ISSUE TITLE
Crash 1.12.2.

### ISSUE THREAD

**Issue by Asvort** [Nova-Committee/BoatOverhaul#4]
Magma - 1.12.2-d04e549e. jar cannot start with the mod: the reason is a non-existent duplicate (even the file names match, although this is impossible).

Duplicate Mods:
    boatoverhaul : /home/container/./mods/BoatOverhaul-Forge-1.12.2-2.0.0-mixinless.jar
    boatoverhaul : /home/container/./mods/BoatOverhaul-Forge-1.12.2-2.0.0-mixinless.jar

net.minecraftforge.fml.common.DuplicateModsFoundException
    at net.minecraftforge.fml.common.Loader.identifyDuplicates(Loader.java:437)
    at net.minecraftforge.fml.common.Loader.identifyMods(Loader.java:399)
    at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:539)
    at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:102)
    at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:337)
    at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:169)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:623)
    at java.lang.Thread.run(Thread.java:748)

**Comment by Asvort** [comment]
I tried to use both a mix and a separate mod with _MixinBootstrap-1.1.0.jar . The same problem.

**Comment by VulpesStella** [comment]
Will rework this soon

**Comment by VulpesStella** [comment]
[BoatOverhaul-Forge-1.12.2-2.0.1-mixinless](https://legacy.curseforge.com/minecraft/mc-mods/boatoverhaul-forge/files/4513401) is uploaded. Should be reviewed and made public soon.

**Comment by Asvort** [comment]
Hi. Sorry for the long ping. The update did not solve the problem, new errors appeared in the logs and the old one remained in the crash.

---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// Sorry :(

Time: 5/20/23 12:09 PM
Description: Exception in server tick loop

Duplicate Mods:
	boatoverhaul : /home/container/./mods/BoatOverhaul-Forge-1.12.2-2.0.1-mixinless.jar
	boatoverhaul : /home/container/./mods/BoatOverhaul-Forge-1.12.2-2.0.1-mixinless.jar

net.minecraftforge.fml.common.DuplicateModsFoundException
	at net.minecraftforge.fml.common.Loader.identifyDuplicates(Loader.java:437)
	at net.minecraftforge.fml.common.Loader.identifyMods(Loader.java:399)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:539)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:102)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:337)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:169)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:623)
	at java.lang.Thread.run(Thread.java:748)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
[latest.log](https://github.com/Nova-Committee/BoatOverhaul/files/11522064/latest.log)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Magma Version: 1.12.2-d04e549e

**Comment by CtrelokCvobods** [comment]
Do I understand correctly that MixinBoots is required?, otherwise the error does not allow the server to start:
[latest.log](https://github.com/Nova-Committee/BoatOverhaul/files/11522077/latest.log)
